### PR TITLE
Bugfix/fix wp cli

### LINKED ISSUE #15: Add a limit to the number of revisions
In order to avoid overloading databases could we add a limit to the number of post revision  to our `wp-config.php` template ? 

`define( 'WP_POST_REVISIONS', 3 );`

### LINKED ISSUE #17: WP CLI from vendor is not working
WP CLI from composer vendor does not work

```bash
▶ ./vendor/bin/wp plugin list
`autoload.php` not found. Did you run `composer install`?%
```

This is failling at the very first line of `wp-config.php` 
`if ( ! file_exists( dirname( __DIR__ ) . '/vendor/autoload.php' ) )`

This is searching for a file in. :
`./vendor/wp-cli/wp-cli/php/vendor/autoload.php`
and not in `./vendor/autoload.php`

### PR DESCRIPTION
**Pull request by perruche**
### Fix WP CLI from vendors
Remove a single quote that was causing a WP CLI regex to fail when resolving the `__FILE__` and `__DIR__` constants.
- Resolve #17

### Add a limit for posts revisions 
Add a default value of 3 to limit the number of posts revisions. The value can be configure through `.env`
- Resolve #15

### CODE REVIEW

File: template/bin/source/wp-config-sample.php [hunk 1]
```diff
@@ -18,13 +18,13 @@
  * @package WordPress
  */
 
-if ( ! file_exists( dirname( __DIR__ ) . '/vendor/autoload.php' ) ) {
+if ( ! file_exists( ABSPATH . '../../vendor/autoload.php' ) ) {
```
Comment (lusimeon) [inline template/bin/source/wp-config-sample.php]: Is it still working when you run the app from webserver?

Instead of updating `wp-config.php` file, I think you can use `--path` command argument to specify in which folder command need to run (see [arguments](https://make.wordpress.org/cli/handbook/references/config/#global-parameters)).

Comment (perruche) [reply template/bin/source/wp-config-sample.php]: I think the `path` option is already set by default via `wp-cli.yml` which contain `path: web/wp/`, i'm not sure how to test it's working. I think this option to to give wp-cli the path to the WordPress core folder, which is `web/wp`, but this is not where the autoload is in our case

I recon that the solution provided in this PR, is kinda bad. But it's working on the webserver. I'm totally down to find a better way to handle this issue 😄

Comment (titouanmathis) [reply template/bin/source/wp-config-sample.php]: I found the origin of the bug!

The WP CLI evaluates the code of the `wp-config.php` (see [Runner.php:1211](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L1211)) file and search and replace each occurrence of the `__DIR__` and `__FILE__` constants with the correct path with the following regex: `/(?>\'[^\']*?\')|(?>"[^"]*?")|(?<file>\b__FILE__\b)|(?<dir>\b__DIR__\b)/m` (see [utils.php:36](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L36) and [Runner.php:612](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L612)).

I tested the content of our `wp-config.php` file and it appears that a single quote in the first comment of the files breaks the regex (see https://regex101.com/r/5BnTCY/1). Replacing this quote with a `’` fixes the bug (see https://regex101.com/r/5BnTCY/2), see the diff below:

```diff
diff --git a/bin/source/wp-config-sample.php b/bin/source/wp-config-sample.php
index fba8e0a..26daddf 100644
--- a/bin/source/wp-config-sample.php
+++ b/bin/source/wp-config-sample.php
@@ -3,7 +3,7 @@
  * The base configuration for WordPress
  *
  * The wp-config.php creation script uses this file during the
- * installation. You don't have to use the web site, you can
+ * installation. You don’t have to use the web site, you can
  * copy this file to "wp-config.php" and fill in the values.
  *
  * This file contains the following configurations:
```

**Review by titouanmathis — CHANGES_REQUESTED** [review]
The WP CLI bug can be fixed by replacing a `'` by a `’`, it should be more robust than using the WordPress defined constant `ABSPATH`.
